#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso phaseChangeReaction
wclean libso phaseChangeReaction/surfaceReaction
wclean libso phaseChangeReaction/solidNucleation
wclean

#------------------------------------------------------------------------------
